spring.application.name=bite-shore
# порт де працює застосунок
server.port=8080
# налаштування бд Н2 база в пам'яті
#spring.datasource.url=jdbc:h2:mem:bite-short
spring.datasource.url=jdbc:postgresql://localhost:5432/bite_short
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres

# створює таблиці автоматично
spring.jpa.hibernate.ddl-auto=update
  # вже не створює це робить флавей
#debug=true
spring.profiles.active=local
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# увімкнути веб консоль Н2 (http://localhost:8080/h2-console)
spring.h2.console.enabled=false
#spring.h2.console.path=/h2-console
# логи SQL (щоб бачити запити)
spring.jpa.show-sql=false



# первинне створення табл Флавей

#spring.jpa.hibernate.ddl-auto=validate

#ремонтую
